name: Trigger job on change of notebooks

on:
  pull_request:
    types: [closed]
    branches: [main]

    paths:
      - "notebooks/*"

jobs:
  run-databricks-job:
    if: github.event.pull_request.merge == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger job
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          JOB_ID: ${{ secrets.JOB_ID }}

        run: |
          pip install databricks-cli
          databricks configure --token --host $DATABRICKS_HOST <<< "$DATABRICKS_TOKEN"
          databricks jobs run-now --job-id $JOB_ID
